created user profile, edited user fixtures+readme
SocialFinanceDigitalLabs/cs-demand-model-regional pull request #21
Opened 2024-03-12 17:02 UTC by amynickolls

created user profile with fields show_instruction and la
user creation in fixtures and readme updated to test la extraction from email address

2024-03-13 11:52 UTC, franciscobmacedo requested changes

2024-03-13 11:52 UTC, franciscobmacedo commented on dm_regional_app/migrations/0003_profile_la.py
> +
Can you avoid having 2 migration files, like we did in our session yesterday?

2024-03-13 11:52 UTC, franciscobmacedo commented on dm_regional_app/signals.py
> +            la = instance.email.split("@")[1].split(".")[0]
what if the email is something like "john.gov.uk@gmail.com"? This will not work. Maybe you can check if the email ends with `.gov.uk` with the string `.endswith` method instead of just checking if `.gov.uk` is there

2024-03-15 10:41 UTC, amynickolls commented on dm_regional_app/migrations/0003_profile_la.py
> +
Is this - only have one migration file for profile, or have one migration overall (init only)?

2024-03-15 11:04 UTC, franciscobmacedo commented on dm_regional_app/migrations/0003_profile_la.py
> +
Yes this it. No, in general you shouldn't change migrations that were  already created before you started doing changes. That would cause an issue in existing databases of this project - for example, the upcoming production database.

2024-03-18 14:45 UTC, merged