52 add costs page
SocialFinanceDigitalLabs/cs-demand-model-regional pull request #53
Opened 2024-07-30 13:02 UTC by amynickolls

Costs (projecting spend) page added.
Some edits to costs.py and models.py to include summary table and proportion adjustments
Able to edit placement costs
Able to edit placement proportions - these should sum to 1 per category
Charts added - area charts for costs and children
Forecast breakdown

Logic to show/hide adjustment options depending on if you have made adjustments. make adjustments on 'adjust forecast' page

2024-08-02 16:28 UTC, MichaelHanksSF requested changes
Hi Amy, thanks for all this mega work - there's some top stuff in here!

I have reviewed this from the perspective of the Python modelling / calculation stuff; not from the perspective of the Django application and html bits.

So broadly, please consider this a review of:
charts.py
utils.py
views.py
costs.py
multinomial.py

And please get Tambe to review:
templates
template_tags
html in views
urls.py

A general point - some more commenting and docstrings would be nice for some of the functions. I found some, like charts.transition_rate_tables() fairly unreadable.

Some actual changes to make please:
- [ ] costs should be by week, not day and the calculations where necessary divide by 7
- [ ] can we work out the adjusted proportion populations as well as costs in the convert_population_to_cost() function (by doing another output which is just the same as lines 171 or 175 but without * cost; then we can just use both of these daily tables (one for adjusted populations and one for adjusted costs) as the inputs for the area_chart_cost and area_chart_population functions. At the moment it feels like there's considerable unneccesary rework calculating these.
- [ ] normalized proportions doesn't account for if the user selects all the placement categories, but the sum of the proportions is <1 - this should be considered
- [ ] does anything prevent -ve costs in the web app? I should check but I'm lazy
- [ ] summary tables is a little overwritten I think and creates the need for a redundant step where you have to make another summary table for the differences (see below)
- [ ] again, year_one_filter feels over-written - can we not just filter the existing summary tables to the first year's quarters and sum the table (2 lines of code instead of 6)?
- [ ] I don't really understand some of the transition_rates_tables etc. especially use of df.pop and df.insert to reorder columns (I think?) and if df.shape[1] == 3 part I didn't follow at all - can we walk through this one?

For the summary_tables():
instead of:
```
    df = (
        df.reset_index()
        .rename(columns={"index": "Placement"})
        .transpose()
        .reset_index()
    )
    df.columns = df.iloc[0]
    df = df[1:]
```
can we try:
```
    df_transposed = df.T
    df_transposed['Placement'] = df_transposed.index
    df_final = df_transposed.reset_index(drop=True).set_index('Placement')
```

For backlog development (after I make my changes to datacontainer *cough*):
historic_data should not have proportion adjustments made, it should simply read in the actual historic proportions

2024-08-06 11:09 UTC, tab1tha commented on dm_regional_app/templatetags/table_tags.py
> +        modified_value = value
If there is no transformation done from line 22 to 23, then maybe both lines could be merged into:
for modified_value in df.columns:
    ....
However, if there is a reason, later on, to use value (not modified_value) then this can be ignored.

2024-08-06 12:34 UTC, tab1tha approved these changes
Added a few comments and I can confirm that this runs locally on my computer also. 
It was quite a task to read through but remained interesting to see all the pieces fit together so well. 
Apart from Michael's comments, the html, template tags and display logic are good to go.
Thank you !

2024-08-07 16:05 UTC, amynickolls commented on dm_regional_app/templatetags/custom_tags.py
> +        html += "<ul>UASC:"
Thank you, unintentional!

2024-08-07 16:16 UTC, amynickolls commented on dm_regional_app/templatetags/table_tags.py
> +    return mark_safe(html)
Flagging this to @MichaelHanksSF as well - I couldn't find another way of implementing, the change was the result of enables this code to be used for proportion and cost adjustment forms as well as rate ones. Tambe's assumptions are correct - string data only comes from within datacontainer and everything else numeric.

2024-08-07 16:40 UTC, amynickolls commented
> again, year_one_filter feels over-written - can we not just filter the existing summary tables to the first year's quarters and sum the table (2 lines of code instead of 6)?

Because the summary tables work on annual quarters rather than from the first date, always doing a quarter, returning year one costs by filtering to the first 4 quarters might not return a full year of costs

> One big benefit of this is that the values remain floats, so you can work out summary_table_difference as just one summary table minus the other, without creating another summary table from the costs.summary table and subtracting these.

I have updated this code but it was remaining float as you didn't have the string column so not changed anything in the view.

2024-08-08 09:47 UTC, MichaelHanksSF commented on dm_regional_app/templatetags/table_tags.py
> +    return mark_safe(html)
Thanks for flagging - can we discuss where mark_safe is used, whether we think that the inputs can be manipulated in any way and then present a basic case to Matthew/Michala?

2024-08-08 09:49 UTC, MichaelHanksSF commented
> @MichaelHanksSF
> 
> > again, year_one_filter feels over-written - can we not just filter the existing summary tables to the first year's quarters and sum the table (2 lines of code instead of 6)?
> 
> Because the summary tables work on annual quarters rather than from the first date, always doing a quarter, returning year one costs by filtering to the first 4 quarters might not return a full year of costs
> 
> > One big benefit of this is that the values remain floats, so you can work out summary_table_difference as just one summary table minus the other, without creating another summary table from the costs.summary table and subtracting these.
> 
> I have updated this code but it was remaining float as you didn't have the string column so not changed anything in the view.

Thanks. On the first point, does this mean that the table that shows quarters also won't show two years' of costs?

On the second, not sure what you mean, perhaps we can discuss?

2024-08-08 10:55 UTC, amynickolls commented
> Thanks. On the first point, does this mean that the table that shows quarters also won't show two years' of costs?
> 
> On the second, not sure what you mean, perhaps we can discuss?

The table that shows quarters currently just quarters the full forecast. We could add logic to restrict this - more than two years stretches the screen out. There is this text at the beginning of the cost breakdown - "Please note that if your prediction start and end dates do not align with the beginning and end of calendar quarters then the first and last quarter in the following tables will not represent a total quarter figure."

On the second - the bootstrap tables work by iterating through the values, so require the placements to be in a column. Your example code drops this column which is what enables one to be subtracted from the other. I could write a new table tag function that also iterates through the index. This would mean having two of these functions so more code there but would mean we can just subtract one from the other. Lets discuss if this doesn't make sense.

2024-09-03 15:40 UTC, MichaelHanksSF approved these changes

2024-09-03 15:40 UTC, merged