changes to costs
SocialFinanceDigitalLabs/cs-demand-model-regional pull request #56
Opened 2024-08-09 15:15 UTC by amynickolls

Creating a new PR for the changes Michael requested since it's a fair bit of code. Tambe's changes are also in here. The last two bullets were my own changes. To review:

- costs by week, not day
- costs.py now outputs populations. also no longer outputs by bin but by placement category
- charts tidied
- charts show detailed placement type
- logic to deal with proportions summing to <1 added
- DynamicForm no longer accepts negative numbers and logic added to views to warn of this
- summary tables - new table tag written for this to allow subtraction of tables. This means additional code but less processing
- bug fix for inflation on GET request
- clear rate adjustment button on costs page now redirects back to costs

2024-08-30 09:36 UTC, MichaelHanksSF requested changes
Hello @amynickolls,

Thanks for making these changes!

I have made a further commit to amend the code for adjusting proportions. This is because the changes you had made still didn't account for instances where:
- the total < 1
- remaining = 0
I've also reduced the number of ifs involved as all scenarios can be covered by three conditions:
- where total = 1
- where adjusted >= 1 or remaining = 0
- else, which will be total != 1,  adjusted < 1 and remaining > 0

One change that I would like you to make please is to align the naming conventions for the CostForecast class and the convert_population_into_cost() function. I find it confusing to read when e.g. the class considers the costs to be the costs per day, but the function considers costs to be the cost_summary list. Can we align these more closely so that each of them has a name that can't be confused with something else and they map to one another?

@tab1tha Could you please review:
- [x] forms.py
- [x] templates and templatetags changes
- [ ] changes in views.py from line 212 down

Thanks!

2024-09-02 11:23 UTC, tab1tha approved these changes

2024-09-02 11:23 UTC, tab1tha commented on dm_regional_app/templatetags/table_tags.py
> +    return html
Nice !

2024-09-03 14:59 UTC, MichaelHanksSF approved these changes

2024-09-03 14:59 UTC, merged