new placement_starts_chart() and associated chgs
SocialFinanceDigitalLabs/cs-demand-model-regional pull request #85
Opened 2024-09-17 12:53 UTC by robjharrison

spelling typo fix on readme

placements counts chart on historic page. includes additional start/end date vars in views to enable possible restriction/changes in timeframe of placements chart. Avg placement duration shows only in plot hover.

2024-09-24 18:12 UTC, amynickolls submitted a review, later dismissed

2024-09-24 18:12 UTC, amynickolls commented on dm_regional_app/charts.py
> +    )
```suggestion
    df_entrants = (
        df_filtered.groupby(["DECOM", "placement_type"])
        .agg(
            count=("CHILD", "size"), avg_duration=("placement_duration", "mean")
        )  # calculate count and avg duration
        .reset_index()
    )
        # Create a range of all months to ensure we have complete months
    all_months = pd.date_range(start=start_date, end=end_date, freq='M')

    # Group by 'placement_type' and aggregate
    df_entrants = (
        df_filtered.groupby(["placement_type", pd.Grouper(key="DECOM", freq="M")])  # Group by month
        .agg(
            count=("CHILD", "size"), 
            avg_duration=("placement_duration", "mean")
        )
        .reset_index()  # Reset index after grouping
    )

    # Reindex the result to include all months and fill missing with 0
    df_entrants = df_entrants.set_index(['DECOM', 'placement_type']).reindex(
        pd.MultiIndex.from_product([all_months, df_entrants['placement_type'].unique()], names=['DECOM', 'placement_type']),
        fill_value=0
    ).reset_index()
```
Need to fill missing months with 0 - this is a fairly convoluted way of doing it - feel free to make it simpler

2024-09-24 18:12 UTC, amynickolls commented on dm_regional_app/templates/dm_regional_app/views/historic.html
> +        <h3>Historic Data</h3>
Remove title - title is within chart

2024-09-24 18:12 UTC, amynickolls commented on dm_regional_app/templates/dm_regional_app/views/historic.html
> +        <h3>Placement Starts</h3>
Remove title - title is within chart

2024-09-24 18:12 UTC, amynickolls commented on dm_regional_app/views.py
> +        chart = historic_chart(stats)  # consider name revision
historic_population_chart?

2024-09-24 18:12 UTC, amynickolls commented on dm_regional_app/views.py
> +        chart = historic_chart(stats)  # consider name revision
On this - perhaps update the title of historic data chart to 'Historic population' (within charts.py)

2024-09-24 18:12 UTC, amynickolls commented on dm_regional_app/charts.py
> +
Need to set axes - x to 0, y to match 1st and last data point (currently some white space either end, I think due to the way years are labelled)

2024-10-02 16:28 UTC, robjharrison commented on dm_regional_app/charts.py
> +
Ah yes, sorry i forgot about those blank ends. Meant to sort that.

2024-10-02 16:30 UTC, robjharrison commented on dm_regional_app/charts.py
> +    data.df["DECOM"] = data.df["DECOM"].dt.to_period("M").dt.to_timestamp()
Not sure how you're getting this to work without this, I've not been able. I'm leaving it in for now as without i've only type incompatibilities on dt.

2024-10-03 08:21 UTC, robjharrison commented
Amy. I've made the changes, excepting the date conversions, see comment. Apologies for the back and forth on this.

2024-10-03 17:01 UTC, amynickolls commented on dm_regional_app/charts.py
> +    data.df["DECOM"] = data.df["DECOM"].dt.to_period("M").dt.to_timestamp()
No problem, it might be a codespaces inconsistency as Will mentioned

2024-10-03 17:07 UTC, amynickolls commented
No problem on the back and forth - afraid I have a couple more requests of you on this!

Thanks for resetting the axes, but could we get a bit of space at the top axis of the chart? As in the historic data chart.

![image](https://github.com/user-attachments/assets/56823f4b-f0f0-4e3c-bf94-a11827ff6232)

I've also just merged in Rob's PR on getting placements into the historic graph. Would you mind merging main into this branch and checking that the colours are consistent for placements across the two graphs? Thanks!

2024-10-03 17:15 UTC, amynickolls reviewed
Apologies as I think I missed these two items re start/end dates and comments in the first review!

2024-10-03 17:15 UTC, amynickolls commented on dm_regional_app/views.py
> +                # end_date = form.cleaned_data["end_date"]
Missed these first time I think - left in comments/outdated comments

2024-10-03 17:15 UTC, amynickolls commented on dm_regional_app/views.py
> +            end_date = form.initial.get("end_date", datacontainer.end_date)
There aren't any dates in the form, so just grab these from datacontainer. You could probably also move these out of the if/else since these should stay the same. I think even where there is a filtered population to cover less time (e.g. no children UASC of a certain age for specific years) we would still want to show in the table that the data was none for that period rather than reducing the period shown in the chart.

2024-10-10 11:17 UTC, robjharrison commented on dm_regional_app/views.py
> +            end_date = form.initial.get("end_date", datacontainer.end_date)
Agreed, have extended this, to the additional removal/refactor of duplicated start/end date retrieval within the IF block. start_date and end_date now only extracted once after datacontainer loaded.

2024-10-10 11:52 UTC, robjharrison commented on dm_regional_app/views.py
> +        chart = historic_chart(stats)  # consider name revision
thanks, edited charts.py

2024-10-25 15:38 UTC, MichaelHanksSF requested changes
Hi Rob, thanks for this work. I like some of the additional touches, like the hover (though see comment below!). 

I have merged this branch with main to add the work that has been done on other graphs, as I thought it might be helpful. You don't need to use this, but as in comments below, we do need to align the colour scheme for this graph with the other graphs in the app.

2024-10-25 15:38 UTC, MichaelHanksSF commented on dm_regional_app/charts.py
> +
Bit more commentary on lines 310-320 would be appreciated

2024-10-25 15:38 UTC, MichaelHanksSF commented on dm_regional_app/charts.py
> +        hover_data={"true_count": True, "avg_duration_weeks": True},
As Amy suggested, the commented out line can be removed.

2024-10-25 15:38 UTC, MichaelHanksSF commented on dm_regional_app/charts.py
> +        ),
I think the title "Date" isn't too informative, when the axis is showing months - can we switch to month?

2024-10-25 15:38 UTC, MichaelHanksSF commented on dm_regional_app/charts.py
> +    df_entrants["true_count"] = df_entrants["count"]
Is there a need for this true count column?

2024-10-25 15:38 UTC, MichaelHanksSF commented on dm_regional_app/charts.py
> +        hovermode="x",
I prefer to not have the hovermode = "x". I think it's more legible when you're only seeing the hover for the line you're looking at.

2024-10-25 15:38 UTC, MichaelHanksSF commented on dm_regional_app/charts.py
> +        ),
Also, this change has the unfortunate effect of switching from showing the year month in the hover to showing the last date of the month for the non quarterly months and just Jan, Apr, Jul for the quarterly months.

2024-10-25 15:38 UTC, MichaelHanksSF commented on dm_regional_app/charts.py
> +    fig.update_traces(line=dict(width=1), marker=dict(size=4))
Is it necessary to call this as a separate function, rather than setting the width and the marker size in the original line function?

2024-10-25 15:38 UTC, MichaelHanksSF commented on dm_regional_app/charts.py
> +    )
Again, fairly sure you can set these in the original graph call?

2024-10-25 15:38 UTC, MichaelHanksSF commented on dm_regional_app/charts.py
> +    )
And again - original graph call?

Happy for you to split that call out on the page to add more commentary, but it seems unnecessary to be creating and re-creating this graph so many times.

2024-10-25 15:38 UTC, MichaelHanksSF commented on dm_regional_app/charts.py
> +    ]
Unfortunately, we have a bigger problem here. The data has been enriched to include new "placements" for when children change age bin categories. This is so that ageing transition rates can be explicitly calculated along with other types of transition. But here, those are not legitimate placement starts, so we need to filter them back out again. You're looking for episodes where the only difference between the previous bin and the current bin is the age bucket.

2024-10-25 15:38 UTC, MichaelHanksSF commented on dm_regional_app/charts.py
> +        color="placement_type",
I would also like alignment with the other graphs in terms of colours. This is achieved in the other graphs by using the util functions add_traces. If you don't use this function (which I think you could if you wanted to from the data you have here), could you align the colours of the lines and add a line for total please?

2024-11-12 16:35 UTC, robjharrison commented on dm_regional_app/charts.py
> +    data.df["DECOM"] = data.df["DECOM"].dt.to_period("M").dt.to_timestamp()
Have removed 287 (data.df["DECOM"] = pd.to_datetime(data.df["DECOM"])), but 289 now still required with subsequent later changes.

2024-11-12 16:57 UTC, robjharrison commented on dm_regional_app/charts.py
> +    df_entrants["true_count"] = df_entrants["count"]
there is not, thanks. This was a run-over from some previously needed chart related coercions.

2024-11-13 08:02 UTC, robjharrison commented on dm_regional_app/charts.py
> +        color="placement_type",
application of add_trace is problematic, despite the data being apparently aligned. Ref: This function wasn't available at the time of initial dev on this ticket. But formatting is now aligned with that and new total line added.

2024-11-13 08:04 UTC, robjharrison commented on dm_regional_app/charts.py
> +        ),
Ah yes, i missed that, month is new label now.  I'm grateful for you spotting the other date anomaly(!).. I need to return to that, not yet resolved.

2024-11-13 08:05 UTC, robjharrison commented on dm_regional_app/charts.py
> +        hovermode="x",
Have now reset this to align with the historic data chart, showing single trace vals.

2024-11-13 08:06 UTC, robjharrison commented on dm_regional_app/charts.py
> +    fig.update_traces(line=dict(width=1), marker=dict(size=4))
Yes this shouldn't be the case. Will refactor.

2024-11-13 08:08 UTC, robjharrison commented on dm_regional_app/charts.py
> +    )
Yes this shouldn't be the case. Will refactor. 
(Some of this was a run-over from a point where getting some of the needed data points to show had been problematic and forced a less than ideal approach)

2024-11-27 17:17 UTC, MichaelHanksSF requested changes
Hi Rob, almost there for sure!

I have a couple of very small changes:
- there's a test comment in line 314 - can we remove this please?
- because of the different tick marks we get an inconsistent view in the hover. Can we fix this by adding as a setting to the first fig.add_trace() call lines 351-360:
hovertemplate="%{x|%b %Y}, %{y}"

This hasn't addressed the issue of the age transitions, but we can address that in a separate PR.

Before you can request the merge, you'll also need to manage the conflicts with main. If this is an issue, can you make your commits for the above changes and I'll do the merge.

Thanks,

Michael

2024-12-16 15:50 UTC, MichaelHanksSF approved these changes

2024-12-16 15:51 UTC, merged