39 update historic data filter
SocialFinanceDigitalLabs/cs-demand-model-regional pull request #97
Opened 2024-10-04 16:53 UTC by amynickolls

Updates to historic data filter:
- Ethnicity and Sex filters added
- Age and Placement Type filters removed
- UASC filtering logic fixed

To complete this:
- Datacontainer work to add Ethnicity column
- UASC logic in datacontainer updated

Additional updates needed due to historic filter change:
- router_handler filter defaults
- custom_tags update (to display filters as text on costs page)

2024-10-10 14:58 UTC, MichaelHanksSF requested changes
Thanks for this!

Couple of changes I think are required.

2024-10-10 14:58 UTC, MichaelHanksSF commented on dm_regional_app/templatetags/custom_tags.py
> +
Is there any reason why lines 42-26 are not done like with UASC below?

2024-10-10 14:58 UTC, MichaelHanksSF commented on dm_regional_app/utils.py
> +        loc = data.ethnicity.astype(str).isin(filters["la"])
This is incorrect - should read filters["ethnicity"]

2024-10-10 14:58 UTC, MichaelHanksSF commented on dm_regional_app/views.py
> +        "sex": [],
I'm not 100%, but shouldn't this be "sex": "all"?

2024-10-10 14:58 UTC, MichaelHanksSF commented on dm_regional_app/views.py
> +                    ethnicity=datacontainer.unique_ethnicity,
Just checking my understanding, but are sex and uasc not here because they have a fixed set of choices?

2024-10-11 09:46 UTC, amynickolls commented on dm_regional_app/templatetags/custom_tags.py
> +
UASC flag in the data is True and False which is understandable to users, however, might be worth updating the UASC code so it reads the same as the filter (Include/Exclude UASC)?

2024-10-11 09:52 UTC, amynickolls commented on dm_regional_app/views.py
> +                    ethnicity=datacontainer.unique_ethnicity,
Yes - placement types and age bins are read from the data and input to the form which allows for users to change these in the datacontainer without needing to update the Django app. We could treat sex in the same way if we wanted, adding an extra column in data container for text description? This might help future-proof it if DFE were to update sex to include gender identity/markers for trans/gender non-conforming children in future.

2024-10-11 09:55 UTC, amynickolls commented on dm_regional_app/views.py
> +                    ethnicity=datacontainer.unique_ethnicity,
But then it's likely that if they were to update to beyond binary we would want to change the filter to multiselect anyway...

2024-10-11 11:15 UTC, MichaelHanksSF commented on dm_regional_app/views.py
> +                    ethnicity=datacontainer.unique_ethnicity,
Yep - makes sense. I think leave as is.

2024-10-11 15:00 UTC, MichaelHanksSF approved these changes

2024-10-11 15:00 UTC, merged